# Generated by Django 3.0.4 on 2020-03-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sal',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
    ]
