# Generated by Django 2.2.1 on 2019-06-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(related_name='patients', to='manytomany.Doctor'),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
